{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "50c918ba-114e-4f60-b626-c1c6f6173a1f",
   "metadata": {},
   "source": [
    "# 🧮 Étude : Figures Géométriques — Aires et Visualisations\n",
    "\n",
    "\n",
    "| Nom | Maimouna Diallo     |\n",
    "| 🆔   300155187            \n",
    "\n",
    "Ce notebook démontre l’utilisation d’une hiérarchie de classes Python :\n",
    "\n",
    "- `Figure` (classe de base)\n",
    "- `Carre`\n",
    "- `Cercle`\n",
    "\n",
    "Puis l'affichage graphique grâce à :\n",
    "\n",
    "- **matplotlib 3.9.2**\n",
    "- **numpy 2.1.3**\n",
    "\n",
    "Nous allons :\n",
    "1. définir les classes dans le notebook  \n",
    "2. créer un carré et un cercle  \n",
    "3. tracer les figures graphiquement  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "fb51cfc0-a0af-4dc1-a56a-b0e9f6d8d778",
   "metadata": {},
   "outputs": [],
   "source": [
    "from carre import Carre\n",
    "from cercle import Cercle\n",
    "from losange import losange\n",
    "from parallelogramme import parallelogramme\n",
    "from cylindre import cylindre\n",
    "from prisme_carre import prisme_carre\n",
    "from prisme_losange import prisme_losange\n",
    "from prisme_parallelogramme import prisme_parallelogramme\n",
    "from sphere import sphere\n",
    "from cone import cone\n",
    "from triangle import Triangle\n",
    "from rectangle import Rectangle\n",
    "from trapeze import Trapeze\n",
    "from ellipse import Ellipse\n",
    "from hexagone import Hexagone\n",
    "\n",
    "\n",
    "c1 = Carre(4)\n",
    "c2 = Cercle(3)\n",
    "c3 = losange(10,8)\n",
    "c4 = parallelogramme(12,7)\n",
    "c5 = cylindre(10,5)\n",
    "c6 = prisme_carre(8,4)\n",
    "c7 = prisme_losange(12,6,2)\n",
    "c8 = prisme_parallelogramme(14,8,9)\n",
    "c9 = sphere(1.33)\n",
    "c10 = cone(0.33, 2)\n",
    "f1 = Triangle(6, 4)\n",
    "f2 = Rectangle(5, 10)\n",
    "f3 = Trapeze(10, 6, 4)\n",
    "f4 = Ellipse(7, 3)\n",
    "f5 = Hexagone(5)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "bb33663c-4ad5-4ac9-abac-30c0f0c32885",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "b7c30d3d-e2b7-4ba4-a000-88479efa17d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_carre(carre):\n",
    "    cote = carre.cote\n",
    "    x = [0, cote, cote, 0, 0]\n",
    "    y = [0, 0, cote, cote, 0]\n",
    "\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Carré — côté={cote}, aire={carre.aire()}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "7024b34e-cbe4-46e5-83b3-f9ea9fe3bc7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_cercle(cercle):\n",
    "    r = cercle.rayon\n",
    "    theta = np.linspace(0, 2*np.pi, 300)\n",
    "\n",
    "    x = r * np.cos(theta)\n",
    "    y = r * np.sin(theta)\n",
    "\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Cercle — rayon={r}, aire={cercle.aire():.2f}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ebf022a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "def afficher_losange(losange):\n",
    "    d1 = losange.d1\n",
    "    d2 = losange.d2\n",
    "\n",
    "    # Coordonnées des sommets du losange (constructeur basé sur diagonales)\n",
    "    x = [0,  d1/2,   0,   -d1/2, 0]\n",
    "    y = [d2/2, 0,  -d2/2, 0,  d2/2]\n",
    "\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(\"Losange — d1={d1}, d2={d2}, aire={losange.aire():.2f}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "b9acc252",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "def afficher_parallelogramme(par):\n",
    "    b = par.b\n",
    "    h = par.h\n",
    "    \n",
    "    # Décalage horizontal du sommet supérieur (pour l'inclinaison)\n",
    "    d = b / 3  # Par exemple: par.decalage = 2\n",
    "\n",
    "    # Coordonnées des 4 sommets\n",
    "    x = [0, b, b + d, d, 0]\n",
    "    y = [0, 0, h, h, 0]\n",
    "\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Parallélogramme — base={b}, hauteur={h}, aire={par.aire():.2f}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "85630372",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'afficher_cylindre' from 'cylindre' (C:\\Users\\Bella\\Developer\\INF1093-201-26H-05\\5.OOP\\300155187\\cylindre.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mImportError\u001b[39m                               Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[17]\u001b[39m\u001b[32m, line 4\u001b[39m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnp\u001b[39;00m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mmpl_toolkits\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mmplot3d\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m Axes3D\n\u001b[32m----> \u001b[39m\u001b[32m4\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mcylindre\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m afficher_cylindre\n\u001b[32m      6\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mafficher_cylindre\u001b[39m(cylindre): \n\u001b[32m      7\u001b[39m     r = cylindre.rayon\n",
      "\u001b[31mImportError\u001b[39m: cannot import name 'afficher_cylindre' from 'cylindre' (C:\\Users\\Bella\\Developer\\INF1093-201-26H-05\\5.OOP\\300155187\\cylindre.py)"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from mpl_toolkits.mplot3d import Axes3D\n",
    "from cylindre import afficher_cylindre\n",
    "\n",
    "def afficher_cylindre(cylindre): \n",
    "    r = cylindre.rayon\n",
    "    h = cylindre.hauteur\n",
    "\n",
    "    # Grille d'angles et de hauteurs\n",
    "    theta = np.linspace(0, 2 * np.pi, 50)\n",
    "    z = np.linspace(0, h, 50)\n",
    "    theta, z = np.meshgrid(theta, z)\n",
    "\n",
    "    # Coordonnées en 3D du cylindre\n",
    "    x = r * np.cos(theta)\n",
    "    y = r * np.sin(theta)\n",
    "\n",
    "    # Figure 3D\n",
    "    fig = plt.figure(figsize=(6, 6))\n",
    "    ax = fig.add_subplot(111, projection=\"3d\")\n",
    "\n",
    "    # Surface latérale\n",
    "    ax.plot_surface(x, y, z, alpha=0.5)\n",
    "\n",
    "    # Base inférieure\n",
    "    ax.plot_surface(r * np.cos(theta), r * np.sin(theta), \n",
    "                    np.zeros_like(theta), alpha=0.7)\n",
    "\n",
    "    # Base supérieure\n",
    "    ax.plot_surface(r * np.cos(theta), r * np.sin(theta), \n",
    "                    h * np.ones_like(theta), alpha=0.7)\n",
    "\n",
    "    # Titre\n",
    "    ax.set_title(f\"Cylindre — rayon={r}, hauteur={h}, volume={cylindre.volume():.2f}\")\n",
    "\n",
    "    # Proportion égale des axes\n",
    "    ax.set_box_aspect([1, 1, 1])\n",
    "\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7475c27a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from mpl_toolkits.mplot3d import Axes3D\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def afficher_prisme_carre(p):\n",
    "    c = p.cote\n",
    "    h = p.hauteur\n",
    "\n",
    "    fig = plt.figure()\n",
    "    ax = fig.add_subplot(111, projection='3d')\n",
    "\n",
    "    x = [0, c, c, 0, 0]\n",
    "    y = [0, 0, c, c, 0]\n",
    "    z_bottom = [0,0,0,0,0]\n",
    "    z_top    = [h,h,h,h,h]\n",
    "\n",
    "    ax.plot3D(x, y, z_bottom)\n",
    "    ax.plot3D(x, y, z_top)\n",
    "\n",
    "    for i in range(4):\n",
    "        ax.plot3D([x[i], x[i]], [y[i], y[i]], [0, h])\n",
    "\n",
    "    ax.set_title(f\"Prisme carré — côté={c}, hauteur={h}, volume={p.volume():.2f}\")\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0747fd0e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_prisme_losange(p):\n",
    "   d1, d2, h = p.d1, p.d2, p.hauteur\n",
    "\n",
    "   x = [0, d1/2, 0, -d1/2, 0]\n",
    "   y = [d2/2, 0, -d2/2, 0, d2/2]\n",
    "\n",
    "   fig = plt.figure()\n",
    "   ax = fig.add_subplot(111, projection='3d')\n",
    "\n",
    "   ax.plot3D(x, y, [0]*5)\n",
    "   ax.plot3D(x, y, [h]*5)\n",
    "\n",
    "   for i in range(4):\n",
    "        ax.plot3D([x[i], x[i]], [y[i], y[i]], [0, h])\n",
    "\n",
    "   ax.set_title(f\"Prisme losange — volume={p.volume():.2f}\")\n",
    "   plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b80387a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_prisme_parallelogramme(p):\n",
    "    b = p.base\n",
    "    h = p.hauteur_parallelo\n",
    "    prof = p.profondeur\n",
    "    d = b / 3\n",
    "\n",
    "    x = [0, b, b+d, d, 0]\n",
    "    y = [0, 0, h, h, 0]\n",
    "\n",
    "    fig = plt.figure()\n",
    "    ax = fig.add_subplot(111, projection='3d')\n",
    "\n",
    "    ax.plot3D(x, y, [0]*5)\n",
    "    ax.plot3D(x, y, [prof]*5)\n",
    "\n",
    "    for i in range(4):\n",
    "        ax.plot3D([x[i], x[i]], [y[i], y[i]], [0, prof])\n",
    "\n",
    "    ax.set_title(f\"Prisme Parallélogramme — volume={p.volume():.2f}\")\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a005a781",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_sphere(s):\n",
    "     r = s.rayon\n",
    "\n",
    "     theta, phi = np.linspace(0, np.pi, 40), np.linspace(0, 2*np.pi, 40)\n",
    "     theta, phi = np.meshgrid(theta, phi)\n",
    "\n",
    "     x = r * np.sin(theta) * np.cos(phi)\n",
    "     y = r * np.sin(theta) * np.sin(phi)\n",
    "     z = r * np.cos(theta)\n",
    "\n",
    "     fig = plt.figure()\n",
    "     ax = fig.add_subplot(111, projection='3d')\n",
    "     ax.plot_surface(x, y, z, alpha=0.3)\n",
    "\n",
    "     ax.set_title(f\"Sphère — rayon={r}, volume={s.volume():.2f}\")\n",
    "     plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7aed6d6c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_cone(c):\n",
    "     r = c.rayon\n",
    "     h = c.hauteur\n",
    "\n",
    "     theta = np.linspace(0, 2*np.pi, 50)\n",
    "     z = np.linspace(0, h, 50)\n",
    "     theta, z = np.meshgrid(theta, z)\n",
    "\n",
    "     x = (r * (1 - z/h)) * np.cos(theta)\n",
    "     y = (r * (1 - z/h)) * np.sin(theta)\n",
    "\n",
    "     fig = plt.figure()\n",
    "     ax = fig.add_subplot(111, projection='3d')\n",
    "     ax.plot_surface(x, y, z, alpha=0.3)\n",
    "\n",
    "     ax.set_title(f\"Cône — rayon={r}, hauteur={h}, volume={c.volume():.2f}\")\n",
    "     plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a84e27d-98ff-49bd-8931-2a2b73141297",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_triangle(t):\n",
    "    b, h = t.base, t.hauteur\n",
    "    x = [0, b, b/2, 0]\n",
    "    y = [0, 0, h, 0]\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Triangle — base={b}, hauteur={h}, aire={t.aire()}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e350c2c3-3b32-435b-8f44-9d01556e24ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_rectangle(r):\n",
    "    l, lo = r.largeur, r.longueur\n",
    "    x = [0, lo, lo, 0, 0]\n",
    "    y = [0, 0, l, l, 0]\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Rectangle — largeur={l}, longueur={lo}, aire={r.aire()}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "195bcd59-1595-402a-86d9-3c24249df03d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_trapeze(t):\n",
    "    bg, bp, h = t.base_grande, t.base_petite, t.hauteur\n",
    "    decalage = (bg - bp) / 2\n",
    "    x = [0, bg, bg - decalage, decalage, 0]\n",
    "    y = [0, 0, h, h, 0]\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Trapèze — grande base={bg}, petite base={bp}, hauteur={h}, aire={t.aire()}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e8dd5d9-8474-44bf-99de-765f8222dc3e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_ellipse(e):\n",
    "    a, b = e.demi_axe_a, e.demi_axe_b\n",
    "    theta = np.linspace(0, 2 * np.pi, 300)\n",
    "    x = a * np.cos(theta)\n",
    "    y = b * np.sin(theta)\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Ellipse — a={a}, b={b}, aire={e.aire():.2f}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "93987bc4-1f4d-4afc-8fe8-ba9d6d5e39aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "def afficher_hexagone(h):\n",
    "    cote = h.cote\n",
    "    angles = np.linspace(0, 2 * np.pi, 7)\n",
    "    x = cote * np.cos(angles)\n",
    "    y = cote * np.sin(angles)\n",
    "    plt.figure(figsize=(5, 5))\n",
    "    plt.plot(x, y)\n",
    "    plt.fill(x, y, alpha=0.3)\n",
    "    plt.title(f\"Hexagone — côté={cote}, aire={h.aire():.2f}\")\n",
    "    plt.axis(\"equal\")\n",
    "    plt.grid(True)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "a383ba23-521c-40a2-8f53-df635cff6ddf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Figure: Carré, côté=4, aire=16\n",
      "Figure: Cercle, rayon=3, aire=28.27\n",
      "Figure: losange, d1=10.0, d2=8.0, aire=40.0\n",
      "Figure: parallelogramme, b=12.0, h=7.0, aire=84.0\n",
      "Figure: cylindre, rayon=10.0, hauteur=5.0, volume=1570.80\n",
      "Figure: prisme carré, cote=8.0, hauteur=4.0, volume=256.00\n",
      "Figure: prisme losange, d1=12.0, d2=6.0, hauteur=2.0, volume=72.00\n",
      "Figure: prisme parallelogramme, base=14.0, hauteur=8.0, profondeur=9.0, volume=1008.00\n",
      "Figure: sphere, rayon=1.33, volume=9.85\n",
      "Figure: cone, rayon=0.33, hauteur=2.0, volume=0.23\n",
      "Figure: Triangle, base=6, hauteur=4, aire=12.0\n",
      "Figure: Rectangle, largeur=5, longueur=10, aire=50\n",
      "Figure: Trapèze, grande base=10, petite base=6, hauteur=4, aire=32.0\n",
      "Figure: Ellipse, demi-axe a=7, demi-axe b=3, aire=65.97\n",
      "Figure: Hexagone, côté=5, aire=64.95\n"
     ]
    }
   ],
   "source": [
    "print(c1.afficher_info())\n",
    "print(c2.afficher_info())\n",
    "print(c3.afficher_info())\n",
    "print(c4.afficher_info())\n",
    "print(c5.afficher_info())\n",
    "print(c6.afficher_info())\n",
    "print(c7.afficher_info())\n",
    "print(c8.afficher_info())\n",
    "print(c9.afficher_info())\n",
    "print(c10.afficher_info())\n",
    "print(f1.afficher_info())\n",
    "print(f2.afficher_info())\n",
    "print(f3.afficher_info())\n",
    "print(f4.afficher_info())\n",
    "print(f5.afficher_info())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9106267-a76c-4958-bcab-4ba8677ef974",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
